
  - name: Install packages
    ansible.builtin.dnf:
      name:
        - htop
        - git
        - curl
        - neovim
        - gnome-tweak-tool
        - zsh
        - vlc
        - fzf
        - hugo
        - kitty
        - nodejs-npm
        - ffmpeg
        - 'lame*'
        - 'gstreamer1-plugins-good-*' 
        - gstreamer1-plugins-base
        - gstreamer1-plugin-openh264
        - gstreamer1-libav
        - '@Development tools'
      exclude:
        - lame-devel
      state: latest
