---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest

  - name: Enable RPM fusion
    dnf:
      name: 
        - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-38.noarch.rpm'
        - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-38.noarch.rpm'
      state: present
  
  - include: rpm-packages.yml

  - name: Set default shell to ZSH
    user:
      name: markon
      shell: /bin/zsh
