---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Enable RPM fusion
    ansible.builtin.dnf:
      name: 
        - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-38.noarch.rpm'
        - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-38.noarch.rpm'
      state: present

  - name: Install packages
    ansible.builtin.dnf:
      name:
        - htop
        - neovim
        - gnome-tweak-tool
        - zsh
        - vlc
        - fzf
        - hugo
        - kitty
        - nodejs-npm
        - ffmpeg
        - 'lame*'
        - 'gstreamer1-plugins-good-*' 
        - gstreamer1-plugins-base
        - gstreamer1-plugin-openh264
        - gstreamer1-libav
        - '@Development tools'
      exclude:
        - lame-devel
      state: latest
